### ISSUE TITLE
Could not find factor function in driver 2vive

### ISSUE THREAD

**Issue by mungewell** [schellingb/PseudoVive#1]
DLL placed as per instructions, however Vserver log shows the following error.

```
Sun Jun 25 2017 16:27:44.047 - Could not find factor function in driver 2vive from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\2vive\bin\win64\driver_2vive.dll.
Sun Jun 25 2017 16:27:44.048 - Unable to load driver 2vive because of error 104. Skipping.
```

**Comment by schellingb** [comment]
Hi,
Thank you for the report!

The interface for OpenVR drivers has changed quite a lot since the initial commit. I updated it to the latest interface and confirmed the faked manufacture and model names in the 'Create System Report' screen.
I don't know of any application out there that still does check these values. Google Earth got updated and does not limit by HMD type anymore as far as I know.
Do you know of any app/game that needs this?

Thanks again for the report and test!

**Comment by mungewell** [comment]
Thanks, that appears to load correctly now.

```
Tue Jun 27 2017 00:14:55.094 -   driver 2vive implements interfaces ITrackedDeviceServerDriver_005 
Tue Jun 27 2017 00:14:55.094 - Loaded server driver 2vive (IServerTrackedDeviceProvider_004) from C:\Program Files (x86)\Steam\steamapps\common\SteamVR\drivers\2vive\bin\win64\driver_2vive.dll
Tue Jun 27 2017 00:14:55.094 - Driver 2vive has no suitable devices.
```

```
Device 1 - Serial Number Headset Vive MV HTC LHR-00000000 Null
Camera Firmware:	Version not available.
VSync to Photons:	0.0111111
Display Frequency:	90
User IPD (m):	0.063
Current Universe ID:	2
Previous Universe ID:	0
```

I am attempting to overcome some issues with 'SteamVR Home' not recognising that virtual controllers I am 'supplying' with VRidgeAPI (1). It doesn't detect the controllers, instead insists that I complete the initial set-up (avatars/etc) using the gamepad, which doesn't appear to work either. 

Unfortunately won't be able to test those until the weekend.

1. https://github.com/RiftCat/vridge-api

**Comment by schellingb** [comment]
Interesting. To get any controllers your OpenVR driver needs to actually provide 2 tracked devices of the controller device class. It seems your driver only provides an HMD?

To get SteamVR to recognize the controllers, the system report needs to list 3 or 4 devices like this:

Device 1 - Headset Vive MV HTC LHR-00000000 HTC <SERIALNO>
Device 2 - Base HTC V2-XD/XE LHB-00000000 HTC <SERIALNO>_Camera0
Device 3 - Controller Vive Controller MV HTC LHR-00000000 HTC <SERIALNO>_Controller_Left
Device 4 - Controller Vive Controller MV HTC LHR-00000001 HTC <SERIALNO>_Controller_Right

Other than changing the manufacture and model names the 2vive driver does not do anything like that.

**Comment by mungewell** [comment]
Yes ;-)
I was only able to fire up the Null driver before weekend. Now with VRidge-API running and my fake controller script I see:

Vserver.log
```
Mon Jul 03 2017 20:46:08.263 - Using existing HMD oculus_vridge.0.8
Mon Jul 03 2017 20:46:29.005 - oculus_vridge: New driver registered (serial VridgeControllerV02ID1) with status 1 
Mon Jul 03 2017 20:46:29.008 - oculus_vridge: New driver registered (serial VridgeControllerV02ID2) with status 1 
Mon Jul 03 2017 20:46:29.012 - oculus_vridge: Controller: VridgeControllerV02ID1 activated with id: 2
Mon Jul 03 2017 20:46:29.012 - oculus_vridge: Controller: VridgeControllerV02ID2 activated with id: 3
```
And
```
Device 3 - Controller Vive Controller MV HTC LHR-00000000 VridgeControllerV02ID1
Supported Buttons:	30064771079
Connected Dongle:	 Version: Unknown Version


Device 4 - Controller Vive Controller MV HTC LHR-00000000 VridgeControllerV02ID2
Supported Buttons:	30064771079
Connected Dongle:	 Version: Unknown Version
```

Unfortunately SteamVR Home still refuses to see the 'controllers' for what they are and display a message about pressing 'Y'. It does accept the fake button presses, I just need to figure out which to send when.
![controllers_dam_it](https://user-images.githubusercontent.com/236907/27813836-e237c61e-6035-11e7-8cfc-4daa40e18815.png)

Don't know why the headset is not listed... it is shown in the VRserver as "Using existing HMD oculus_vridge.0.8", maybe I can just fire up (yet) another controller... doesn't change welcome panel. :-(
```
Device 5 - Controller Vive Controller MV HTC LHR-00000000 VridgeControllerV02ID3
Supported Buttons:	30064771079
Connected Dongle:	 Version: Unknown Version
```

**Comment by Bluscream** [comment]
> I don't know of any application out there that still does check these values. Google Earth got updated and does not limit by HMD type anymore as far as I know.
Do you know of any app/game that needs this?

1: [Wolfenstein: Cyberpilot](https://www.pcgamingwiki.com/wiki/Wolfenstein:_Cyberpilot#VR_support) does not support Oculus Devices (but does work with 2vive)
2: Maybe [FS2020](https://www.pcgamingwiki.com/wiki/Microsoft_Flight_Simulator_(2020)#VR_support) will work with this. They announced that the game will only support WMR devices on launch
3: [Halo: Recruit](https://www.pcgamingwiki.com/wiki/Halo_Recruit#VR_support) does only support WMR
