### ISSUE TITLE
not work wih driver4vr

### ISSUE THREAD

**Issue by danank92** [schellingb/PseudoVive#2]
driver4vr not detect my hmd if i use pseudovive.. why??

**Comment by gb2111** [comment]
i think this driver is changing name of driver4vr and so client app cannot find it.
is there way to leave driver4vr named driver with name not changed?

thanks.

**Comment by schellingb** [comment]
All this driver does is rename the connected devices so they resemble an HTC Vive kit.
The original use was for applications like Google Earth VR back when it contained a device check and refused to start up without something named Vive. Nowadays Google Earth VR does not check this anymore as far as I know so I'm not even sure if it's needed anymore.

It overwrites 5 text strings reported from any active OpenVR driver:
- Forces manufacturer string to "HTC"
- Forces HMD device model number to "Vive MV HTC LHR-00000000"
- Forces tracking device model number to "HTC V2-XD/XE LHB-00000000"
- Forces left motion controller model number to "Vive Controller MV HTC LHR-00000000"
- Forces right motion controller model number to "Vive Controller MV HTC LHR-00000001"

It doesn't try to hide drivers or change any other identification but I guess it could be possible for some driver4vr related software to be confused by the changed model and manufacturer names.

Can you post what appears in the "Devices" tab of the system report? You can view it by right-clicking the SteamVR icon and selecting "Create System Report".

**Comment by gb2111** [comment]
[steamvr system report.txt](https://github.com/schellingb/PseudoVive/files/1332142/steamvr.system.report.txt)

![obraz](https://user-images.githubusercontent.com/22025896/30847599-623ddfee-a29c-11e7-9776-87effac6f31b.png)

![obraz](https://user-images.githubusercontent.com/22025896/30847641-8d10211e-a29c-11e7-867b-f039c5e2034c.png)


Please find attached report and screen from my tool. i need name driver4vr to be found by name. i guess you change it so I cannot find it...

**Comment by schellingb** [comment]
Do you have access to the source code of the driver4vr OpenVR driver? If so you can directly modify your IVRProperties interface to return HTC vive strings directly and have no need for PseudoVive. Again all PseudoVive (the 2vive driver) does is rename things. If you don't want things renamed, you can just remove driver_2vive.dll because that's all it does.
Maybe Driver4VR can directly offer an option to fake the device names to HTC Vive?

**Comment by gb2111** [comment]
it has been implemented now in driver4vr. 
thanks for help.
greg
