### ISSUE TITLE
Build from source

### ISSUE THREAD

**Issue by DantaliaN00** [schellingb/PseudoVive#4]
When I trying to build it I get

```
1>driver_2vive.obj : error LNK2001: unresolved external symbol __Init_thread_epoch
1>driver_2vive.obj : error LNK2001: unresolved external symbol __Init_thread_footer
1>driver_2vive.obj : error LNK2001: unresolved external symbol __Init_thread_header

and in debug mode something like
error LNK2001: unresolved external symbol _CrtDbgReportW
```

I tried to change MinHook to v1.3.3 same error

Visual Studio 2017 (v141) and 2017 (v140)

Please help

**Comment by DantaliaN00** [comment]
For some strange reasons I can't build from source in VS2017/2015 as is
But if I create new dll-project and copy-paste source code step by step I finally make worked dll!

**Comment by Bluscream** [comment]
@DantaliaN00 can you share your repo?
