### ISSUE TITLE
Cant be remove ever

### ISSUE THREAD

**Issue by Guizmo12** [schellingb/PseudoVive#8]
It cant be deactivated for good. Cant be remove. I have tryied to delete every single peices of this code and every single time I reopen steamVR is magicly reapear in the task bar and regreate it self from thin hair....

**Comment by schellingb** [comment]
I can assure you if you remove the '2vive' folder out of the 'drivers' folder of SteamVR it will be fully removed. PseudoVive does not do any permanent change it is only active if the file exists.

If you're unsure how to delete it, just search your computer for two files named "driver_2vive.dll" and delete them.
